from __future__ import annotations

import os
import sys
from pathlib import Path

# Ensure the live backend repo (src.*, scripts.*) is importable, taking
# priority over multimedia-rag/, which only holds a stale, pre-backend-update
# copy of src/. Without this order, `import src.transcript_retrieval` (and
# other new modules) would silently resolve to the outdated copy or fail.
_DASHBOARD_ROOT = Path(__file__).resolve().parent.parent   # castle-rag-dashboard-2/
_MMA_ROOT = _DASHBOARD_ROOT.parent                         # multimedia-rag/
_BACKEND_ROOT = Path(
    os.getenv("CASTLE_BACKEND_ROOT", "/gpfs/scratch1/shared/group_h/data_goncalo")
)
# Keep the checked-in backend as the source of truth. The shared backend root
# still provides data/model assets, but must not silently shadow src/ changes
# made in this repository.
for _root in (_BACKEND_ROOT, _MMA_ROOT):  # inserted in reverse priority order
    _root_str = str(_root)
    if _root_str in sys.path:
        sys.path.remove(_root_str)
    sys.path.insert(0, _root_str)

from dash import Dash
from dotenv import load_dotenv

# Load configuration before callbacks import the pipeline module and bind its
# model/index settings.
load_dotenv(_DASHBOARD_ROOT / ".env")

from castle_dashboard.callbacks.dashboard_callbacks import register_callbacks
from castle_dashboard.components.layout import build_layout


def create_app() -> Dash:
    app = Dash(
        __name__,
        title="CASTLE RAG Dashboard",
        suppress_callback_exceptions=True,
        assets_folder=str(_DASHBOARD_ROOT / "assets"),
    )
    app.layout = build_layout()
    register_callbacks(app)
    _register_image_routes(app)
    return app


def _register_image_routes(app: Dash) -> None:
    """Flask routes for serving keyframe and grounding images from absolute paths."""
    from flask import abort, request, send_file

    _ALLOWED_PREFIXES = (
        "/gpfs/scratch1/shared/group_h/data_goncalo/day1/",
        "/scratch-shared/group_h/data_goncalo/day1/",
    )

    @app.server.route("/keyframe")
    def serve_keyframe():
        path = request.args.get("path", "")
        if not any(path.startswith(p) for p in _ALLOWED_PREFIXES):
            abort(403)
        if not os.path.isfile(path):
            abort(404)
        return send_file(path, mimetype="image/jpeg")

    @app.server.route("/grounding/<path:relpath>")
    def serve_grounding(relpath):
        # Grounding outputs are generated by the checked-in src package under
        # the repository root. Older/shared-backend runs may still write under
        # CASTLE_BACKEND_ROOT, so support both roots without allowing arbitrary
        # filesystem paths.
        for root in (_MMA_ROOT, _BACKEND_ROOT):
            candidate = (root / relpath).resolve()
            allowed_dir = (root / "artifacts" / "visual_grounding").resolve()
            if candidate.parent == allowed_dir and candidate.is_file():
                return send_file(str(candidate), mimetype="image/jpeg")
        abort(404)
